// gendocs renders the hand-picked examples in examples.go through the real
// htmlterm engine and writes docs/examples/: one markdown page per example
// (title, HTML/CSS input, and the plain-text terminal output, all readable
// on GitHub as-is), one SVG per example (the same output with color and
// style, since GitHub strips the style attribute from raw HTML embedded in
// markdown, so an <img> is the only way color survives being embedded
// there), one aggregated gallery.html (the same output again, this time as
// real <span style="..."> HTML for a standalone webpage, where a real
// browser resolves the CSS itself and GitHub's sanitizer never runs), and
// an index README.md linking every example page.
//
// Nothing here is validated against a "want" the way the test suite is:
// this is documentation, generated fresh from the current renderer every
// run, so it can't drift out of sync with it. Run it after a change that
// affects rendering, and commit the result:
//
//	go run ./cmd/gendocs
package main

import (
	"fmt"
	"html"
	"os"
	"path/filepath"
	"strings"

	"github.com/charmbracelet/colorprofile"
	"github.com/client9/htmlterm"
	"github.com/client9/htmlterm/internal/ansidecode"
)

const outDir = "docs/examples"

func main() {
	os.Exit(run())
}

func run() int {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
		return 1
	}

	var galleryFragments []string
	var indexEntries []string

	for _, ex := range examples {
		width := ex.Width
		if width == 0 {
			width = 40
		}
		r, err := htmlterm.New(htmlterm.Options{
			CSS:     ex.CSS,
			Width:   width,
			Profile: colorprofile.TrueColor,
		})
		if err != nil {
			fmt.Fprintf(os.Stderr, "gendocs: %s: New: %v\n", ex.Slug, err)
			return 1
		}
		out, err := r.Render(ex.HTML)
		if err != nil {
			fmt.Fprintf(os.Stderr, "gendocs: %s: Render: %v\n", ex.Slug, err)
			return 1
		}

		lines := ansidecode.Parse(out)
		plain := ansidecode.PlainText(lines)
		svg := ansidecode.ToSVG(lines, ansidecode.SVGOptions{})
		htmlFragment := ansidecode.ToHTML(lines, ansidecode.HTMLOptions{})

		svgPath := filepath.Join(outDir, ex.Slug+".svg")
		if err := os.WriteFile(svgPath, []byte(svg), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
			return 1
		}

		mdPath := filepath.Join(outDir, ex.Slug+".md")
		if err := os.WriteFile(mdPath, []byte(exampleMarkdown(ex, plain)), 0o644); err != nil {
			fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
			return 1
		}

		galleryFragments = append(galleryFragments, galleryEntry(ex, htmlFragment))
		indexEntries = append(indexEntries, fmt.Sprintf("- [%s](%s.md) — %s", ex.Title, ex.Slug, ex.Description))
	}

	galleryPath := filepath.Join(outDir, "gallery.html")
	if err := os.WriteFile(galleryPath, []byte(galleryHTML(galleryFragments)), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
		return 1
	}

	indexPath := filepath.Join(outDir, "README.md")
	if err := os.WriteFile(indexPath, []byte(indexMarkdown(indexEntries)), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "gendocs: %v\n", err)
		return 1
	}

	fmt.Printf("gendocs: wrote %d examples to %s\n", len(examples), outDir)
	return 0
}

// exampleMarkdown is deliberately plain-text-only for Output: the .svg
// sits alongside it for color, embedded as an image so GitHub renders it
// without needing to interpret any HTML or ANSI itself.
func exampleMarkdown(ex Example, plain string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# %s\n\n", ex.Title)
	fmt.Fprintf(&b, "%s\n\n", ex.Description)
	b.WriteString("## Input\n\n")
	if ex.CSS != "" {
		fmt.Fprintf(&b, "```css\n%s\n```\n\n", strings.TrimSpace(ex.CSS))
	}
	fmt.Fprintf(&b, "```html\n%s\n```\n\n", strings.TrimSpace(ex.HTML))
	b.WriteString("## Output\n\n")
	b.WriteString("Plain text, character-exact including wrapping and borders:\n\n")
	fmt.Fprintf(&b, "```text\n%s\n```\n\n", plain)
	b.WriteString("With color and style:\n\n")
	fmt.Fprintf(&b, "![%s](%s.svg)\n", ex.Title, ex.Slug)
	return b.String()
}

func indexMarkdown(entries []string) string {
	var b strings.Builder
	b.WriteString("# htmlterm examples\n\n")
	b.WriteString("Generated by `go run ./cmd/gendocs` from the examples in cmd/gendocs/examples.go.\n")
	b.WriteString("Regenerate after any rendering change; nothing here is hand-edited.\n\n")
	b.WriteString(strings.Join(entries, "\n"))
	b.WriteString("\n\nSee also [gallery.html](gallery.html), the same examples as a single\nstandalone page with real colored HTML instead of an image per example.\n")
	return b.String()
}

func galleryEntry(ex Example, fragment string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "<section>\n<h2>%s</h2>\n<p>%s</p>\n", html.EscapeString(ex.Title), html.EscapeString(ex.Description))
	fmt.Fprintf(&b, "<h3>Input</h3>\n<pre class=\"input\">%s</pre>\n", html.EscapeString(strings.TrimSpace(ex.HTML)))
	b.WriteString("<h3>Output</h3>\n")
	b.WriteString(fragment)
	b.WriteString("</section>\n")
	return b.String()
}

func galleryHTML(fragments []string) string {
	var b strings.Builder
	b.WriteString("<!doctype html>\n<html><head><meta charset=\"utf-8\">\n")
	b.WriteString("<title>htmlterm examples</title>\n<style>\n")
	b.WriteString(`
body { background:#0d1117; color:#d4d4d4; font-family:system-ui,sans-serif; max-width:840px; margin:2rem auto; padding:0 1rem; }
h1,h2 { color:#ffffff; }
section { margin-bottom:3rem; }
pre { overflow-x:auto; padding:0.75rem 1rem; border-radius:4px; }
pre.input { background:#161b22; color:#8b949e; }
`)
	b.WriteString("</style></head><body>\n")
	b.WriteString("<h1>htmlterm examples</h1>\n")
	b.WriteString("<p>Generated by <code>go run ./cmd/gendocs</code>. Each Output block below is\n")
	b.WriteString("real HTML produced by ansidecode.ToHTML from the engine's actual rendered\n")
	b.WriteString("output, not a screenshot or a hand-styled approximation.</p>\n")
	for _, f := range fragments {
		b.WriteString(f)
	}
	b.WriteString("</body></html>\n")
	return b.String()
}
